#!/bin/bash

BASEDIR="$(dirname $0)"

set -e

if [[ ! -e qlfile ]] || [[ ! -e app-deps.asd ]]; then
    echo 'Add this line to your Dockerfile'
    echo 'COPY qlfile qlfile.lock app-deps.asd /app/'
    exit 1
fi


qlot install

# Use `qlot exec gen-deps-system app`
# to regenerate app-deps.asd file
qlot exec "${BASEDIR}/install-dependencies.ros"

# qlot exec ros \
#     --eval '(handler-case (ql:quickload "app-deps") \
#                (error (c) \
#                   (format t "~%~%ERROR: ~A~%~%" c) \
#                   #+sbcl(sb-debug:print-backtrace :count 7) \
#                   #+ccl(ccl:print-call-history) \
#                   (uiop:quit 1)))'
